version: 1.4.0.{build}
image: WMF 5

install:
    - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - npm install -g gulp    
    - npm install  
    - ps: |
        Import-Module "$env:APPVEYOR_BUILD_FOLDER\.appveyor\appveyor.psm1"
        Start-AppveyorInstallTask
        
build: off

test_script:
    - ps: |
        Start-AppveyorTestScriptTask

after_test:
    - ps: |
        Start-AppveyorAfterTestTask
