version: 0.2.0.{build}

install:
    - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe   
    - ps: |
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
        Install-Module Pester -Force
        git clone -q https://github.com/PowerShell/DscResource.Tests "$env:APPVEYOR_BUILD_FOLDER\Modules\OfficeOnlineServerDsc\DscResource.Tests"
        Import-Module "$env:APPVEYOR_BUILD_FOLDER\Modules\OfficeOnlineServerDsc\DscResource.Tests\TestHelper.psm1" -force
        

build: off

test_script:
    - ps: |
        $testResultsFile = ".\TestsResults.xml"
        $testCoverageFiles = @()
        Import-Module "$env:APPVEYOR_BUILD_FOLDER\Tests\Unit\OfficeOnlineServerDsc.TestHarness.psm1"
        $res = Invoke-OosDscUnitTestSuite -TestResultsFile $testResultsFile -DscTestsPath "$env:APPVEYOR_BUILD_FOLDER\Modules\OfficeOnlineServerDsc\DscResource.Tests"
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($res.FailedCount -gt 0) { 
            throw "$($res.FailedCount) tests failed."
        }

after_test:
    - ps: |
        Move-Item "$env:APPVEYOR_BUILD_FOLDER\Modules\OfficeOnlineServerDsc\DscResource.Tests" "$env:APPVEYOR_BUILD_FOLDER\"
        Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\TestHelper.psm1" -force

        $manifest = Join-Path "$env:APPVEYOR_BUILD_FOLDER\modules\OfficeOnlineServerDsc" "OfficeOnlineServerDsc.psd1"
        (Get-Content $manifest -Raw).Replace("0.2.0.0", $env:APPVEYOR_BUILD_VERSION) | Out-File $manifest
        Add-Type -assemblyname System.IO.Compression.FileSystem
        $zipFileName = "OfficeOnlineServerDsc_$($env:APPVEYOR_BUILD_VERSION).zip"
        [System.IO.Compression.ZipFile]::CreateFromDirectory("$env:APPVEYOR_BUILD_FOLDER\modules\OfficeOnlineServerDsc", "$env:APPVEYOR_BUILD_FOLDER\$zipFileName")
        New-DscChecksum -Path $env:APPVEYOR_BUILD_FOLDER -Outpath $env:APPVEYOR_BUILD_FOLDER
        Get-ChildItem "$env:APPVEYOR_BUILD_FOLDER\$zipFileName" | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
        Get-ChildItem "$env:APPVEYOR_BUILD_FOLDER\$zipFileName.checksum" | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
        
        cd "$env:APPVEYOR_BUILD_FOLDER\modules\OfficeOnlineServerDsc"
        New-Nuspec -packageName "OfficeOnlineServerDsc" -version $env:APPVEYOR_BUILD_VERSION -author "Microsoft" -owners "Microsoft" -licenseUrl "https://github.com/PowerShell/DscResources/blob/master/LICENSE" -projectUrl "https://github.com/$($env:APPVEYOR_REPO_NAME)" -packageDescription "OfficeOnlineServerDsc" -tags "DesiredStateConfiguration DSC DSCResourceKit" -destinationPath .
        nuget pack ".\OfficeOnlineServerDsc.nuspec" -outputdirectory $env:APPVEYOR_BUILD_FOLDER
        $nuGetPackageName = "OfficeOnlineServerDsc." + $env:APPVEYOR_BUILD_VERSION + ".nupkg"
        Get-ChildItem "$env:APPVEYOR_BUILD_FOLDER\$nuGetPackageName" | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
